config/routes.rb
Realizafera::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  root 'home#index'

  get 'chief/graphic' => 'chief#graphic'
  get 'graphic' => 'graphics#show'
  get 'my_productions' => 'productions#my_productions'
  get 'user_annulments' => 'productions#user_annulments'
  get 'exchange' => 'productions#exchange'
  get 'available_productions' => 'productions#available_productions'

  resources :productions do
    member do
      get :cancel
      get :claim
    end
  end
  resources :free_spots
end

app/models/production.rb
class Production < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  belongs_to :user

  validates :start_day,                 inclusion: { in: (0..6)  }
  validates :end_day,                   inclusion: { in: (0..7)  }
  validates :start_hour, :end_hour,     inclusion: { in: (0..23) }
  validates :start_minute, :end_minute, inclusion: { in: (0..59) }

  validate :too_long_validator
  validate :too_short_validator
  validate :overlapping_validator
  validate :negative_time_validator

  before_validation :check_end_day

  scope :assigned, -> { where.not(user_id: nil) }
  scope :not_assigned, -> { where(user_id: nil) }

  attr_accessible :start_day,
                  :start_hour,
                  :start_minute,
                  :end_day,
                  :end_hour,
                  :end_minute,
                  :repetitive,
                  :cancelled,
                  :user_id

  DAYS = ['niedziela', 'poniedziałek', 'wtorek', 'środa', 'czwartek', 'piątek', 'sobota']

  def self.incident_with_wday(wday)
    where('start_day <= ? AND ? <= end_day', wday, wday)
  end

  def in_progress
    if (start_day == end_day)
      if Time.now.wday == start_day && Time.now.hour > start_hour && Time.now.hour < end_hour
        return true
      else
        return false
      end
    else
      if (Time.now.wday == start_day && Time.now.hour > start_hour) || (Time.now.hour < end_hour)
        return true
      else
        return false
      end
    end
  end

  def self.clean_ongoing_productions
    # This method is regularly called by cron
    Production.all.each do |prod|
      if prod.repetitive && prod.in_progress
        prod.update_attribute(:reminded, false)
      end
    end
  end

  private

  def check_end_day
    self.end_day += 7 if self.start_day > self.end_day
  end

  def too_long_validator
    too_long = (end_day - start_day > 1) || (end_day < start_day)
    errors.add(:end_day, "You can't define a production longer than day") if too_long
  end

  def too_short_validator
    too_short = (start_day == end_day) && (start_hour == end_hour) && (start_minute == end_minute)
    errors.add(:end_day, "You can't define a production that lasts 0 minutes") if too_short
  end

  def negative_time_validator
    negative_time = (start_day == end_day) && (start_hour > end_hour)
    negative_time ||= (start_day == end_day) && (start_hour == end_hour) && (start_minute > end_minute)
    errors.add(:end_day, "You can't define a production has less than 0 minutes") if negative_time
  end

  def overlapping_validator
    no_overlapping_productions = self.class.where("start_day <= ? AND (start_hour * 60 + start_minute < ?)"\
      "AND end_day >= ? AND (end_hour * 60 + end_minute > ?)", end_day, end_hour * 60 + end_minute,
                                                                start_day, start_hour * 60 + start_minute)
    no_overlapping_productions = no_overlapping_productions.where('id != ?', id) if id.present?
    no_overlapping_productions = no_overlapping_productions.count
    errors.add(:start_day, 'This production overlaps with another one') unless no_overlapping_productions.zero?
  end
end

app/controllers/productions_controller.rb
class ProductionsController < ApplicationController
  expose(:production, attributes: :production_params)
  expose_decorated(:user_productions, decorator: ProductionDecorator) {
    Production.where('user_id = :curr_user AND cancelled = false', curr_user: current_user)
  }
  expose_decorated(:cancelled_user_productions, decorator: ProductionDecorator) {
    Production.where('user_id = :curr_user AND cancelled = true', curr_user: current_user)
  }
  expose_decorated(:cancelled_productions, decorator: ProductionDecorator) {
    Production.where(cancelled: true)
  }
  expose_decorated(:free_productions, decorator: ProductionDecorator) {
    Production.not_assigned
  }

  respond_to :json
  respond_to :html, only: [:update, :my_productions, :user_annulments]

  before_action :authenticate_admin_user!, only: [:create, :destroy, :edit]

  alias_method :resource, :production

  def create
    save_resource(:created)
  end

  def update
    respond_to do |format|
      format.html { edit_resource }
      format.json { save_resource }
    end
  end

  def destroy
    resource.destroy
    render json: {}
  end

  def my_productions; end

  def user_annulments; end

  def exchange; end

  def available_productions; end

  def cancel
    flash[:notice] = 'Anulowano realizacje. ...a może jednak dasz radę się pojawić? :)'
    free_users = FreeSpot.available_people(
      production.start_day,
      production.end_day,
      production.start_hour,
      production.end_hour,
      current_user.id
    )
    production.update_attribute(:cancelled, true)
    ProductionMailer.send_production_opening current_user, free_users, production
    redirect_to user_annulments_path
  end

  def claim
    if production.user_id == current_user.id
      flash[:error] = 'Przejąłeś swoją własną realizacje... Na pewno o to Ci chodziło? o_O'
    end
    if production.update_attributes(cancelled: false, user_id: current_user.id)
      flash[:success] = 'Przejąłeś realizację! :) Dzięki za pomoc!'
    else
      flash[:error] = 'Coś poszło bardzo nie tak... Jeśli realizacja nie pojawiła się w Twoim profilu skontaktuj się z Szefem Studia Emisyjnego, by zrobił to ręcznie.'
    end
    redirect_to my_productions_path
  end

  private

  def save_resource(status = :ok)
    status = resource.save ? status : 422
    render json: resource, status: status
  end

  def edit_resource
    if production.update_attributes!(production_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def production_params
    params.require(:production).slice(:start_day, :start_hour, :start_minute, :end_day, :end_hour, :end_minute, :repetitive, :cancelled, :user_id)
  end
end

app/views/productions/available_productions.html.haml
.container
  %h2 Wolne realizacje
  .panel.panel-warning
    .panel-heading
      .panel-title
        Tutaj znajdują się wszystkie nie przypisane jeszcze realizacje. Masz wtedy czas? Przygarnij jedną! :) ...albo cztery.
  - if free_productions.any?
    %table.table.table-hover
      %thead
        %tr
          %td Start
          %td Koniec
          %td Actions
      %tbody
        - free_productions.each do |prod|
          %tr
            %td= prod.start_date
            %td= prod.end_date
            %td
              = link_to claim_production_path(prod), data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' do
                %span.glyphicon.glyphicon-heart
                  %strong Przygarnij realizację
  - else
    .panel.panel-success
      .panel-heading
        .panel-title
          Pusto! Afera jest uratowana! :)

app/views/productions/edit.html.haml
.container
  = simple_form_for production, html: { class: 'form-horizontal' } do |f|
    .row
      .col-lg-12
        = f.label :user
        = f.collection_select :user_id, User.all, :id, :email
    .row
      .col-lg-12
        = f.submit 'Save', class: 'btn btn-default'

app/views/productions/exchange.html.haml
.container
  %h2 Giełda realizacji
  .panel.panel-info
    .panel-heading
      .panel-title
        Tutaj znajdują się anulowane realizacje oczekujące na przejęcie. Nie ignoruj ich, każdy czasem powinien mieć wolne, więc wspomóż kolegę/koleżankę. ;)
  - if cancelled_productions.any?
    %table.table.table-hover
      %thead
        %tr
          %td Anulował\a
          %td Od
          %td Do
          %td Actions
      %tbody
        - cancelled_productions.each do |prod|
          %tr
            %td= prod.user.name
            %td= prod.start_date
            %td= prod.end_date
            %td
              = link_to claim_production_path(prod), data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' do
                %span.glyphicon.glyphicon-refresh
                  %strong Przejmij!
  - else
    .panel.panel-success
      .panel-heading
        .panel-title
          Giełda jest pusta! :)

app/views/productions/my_productions.html.haml
.container
  %h2 Moje realizacje
  .panel.panel-info
    .panel-heading
      .panel-title
        Tutaj znajdują się Twoje realizacje. :) Nie zaśpij! ;)
  - if user_productions.any?
    %table.table.table-hover
      %thead
        %tr
          %td Od
          %td Do
          %td Akcje
      %tbody
        - user_productions.each do |prod|
          %tr
            %td= prod.start_date
            %td= prod.end_date
            %td
              = link_to cancel_production_path(prod), data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
                %span.glyphicon.glyphicon-remove
                  %strong Anuluj realizację
  - else
    .panel.panel-danger
      .panel-heading
        .panel-title
          Nie masz żadnych zaplanowanych realizacji! Tak nie może być!

app/views/productions/user_annulments.html.haml
.container
  %h2 Moje anulowane realizacje
  .panel.panel-warning
    .panel-heading
      .panel-title
        Tutaj znajdują się Twoje anulowane realizacje oczekujące na przejęcie. Nie ignoruj ich, podejmij kroki, by zostały przejęte!
  - if cancelled_user_productions.any?
    %table.table.table-hover
      %thead
        %tr
          %td Od
          %td Do
          %td Actions
      %tbody
        - cancelled_user_productions.each do |prod|
          %tr
            %td= prod.start_date
            %td= prod.end_date
            %td
              = link_to claim_production_path(prod), data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' do
                %span.glyphicon.glyphicon-refresh
                  %strong Anuluj anulowanie... (zdecyduj się?)
  - else
    .panel.panel-success
      .panel-heading
        .panel-title
          Nie anulowałeś żadnych realizacji :) jeszcze... ;)