config/routes.rb
Realizafera::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  root 'home#index'

  get 'chief/graphic' => 'chief#graphic'
  get 'graphic' => 'graphics#show'
  get 'my_productions' => 'productions#my_productions'
  get 'user_annulments' => 'productions#user_annulments'
  get 'exchange' => 'productions#exchange'
  get 'available_productions' => 'productions#available_productions'

  resources :productions do
    member do
      get :cancel
      get :claim
    end
  end
  resources :free_spots
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  expose(:productions) { Production.all.decorate.sort_by { |p| [p.start_day, p.start_hour, p.start_minute] } }

  def index
  end
end

app/views/home/index.html.haml
.container
  .container-fluid
    - Production::DAYS.each_with_index do |day, index|
      .row
        = day
        .col-lg-12
          - productions.select { |p| p.start_day == index }.each do |production|
            - if user_is_admin?
              = link_to edit_production_path(production) do
                .col-lg-2.production
                  .producer
                    - if production.user.present?
                      = production.user.name
                    - else
                      Pusto!
                  .timeline
                    .pull-left
                      = "#{production.start_hour}:#{production.start_minute}"
                    .pull-right
                      = "#{production.end_hour}:#{production.end_minute}"
            - else
              .col-lg-2.production
                .producer
                  - if production.user.present?
                    = production.user.name
                  - else
                    Pusto!
                .timeline
                  .pull-left
                    = "#{production.start_hour}:#{production.start_minute}"
                  .pull-right
                    = "#{production.end_hour}:#{production.end_minute}"