config/routes.rb
Realizafera::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  root 'home#index'

  get 'chief/graphic' => 'chief#graphic'
  get 'graphic' => 'graphics#show'
  get 'my_productions' => 'productions#my_productions'
  get 'user_annulments' => 'productions#user_annulments'
  get 'exchange' => 'productions#exchange'
  get 'available_productions' => 'productions#available_productions'

  resources :productions do
    member do
      get :cancel
      get :claim
    end
  end
  resources :free_spots
end

app/models/free_spot.rb
class FreeSpot < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  belongs_to :user

  validates :user_id, presence: true
  validates :start_day, :end_day,       inclusion: { in: (0..6)  }
  validates :start_hour, :end_hour,     inclusion: { in: (0..23) }
  validates :start_minute, :end_minute, inclusion: { in: (0..59) }

  attr_accessible :start_day,
                  :end_day,
                  :start_hour,
                  :end_hour,
                  :start_minute,
                  :end_minute

  DAYS = {
    'niedziela' => '0',
    'poniedziałek' => '1',
    'wtorek' => '2',
    'środa' => '3',
    'czwartek' => '4',
    'piątek' => '5',
    'sobota' => '6',
  }

  def self.available_people dstart, dend, hstart, hend, current_user_id
    available_users = []
    available_users << self.where('
      start_day <= :wday_start AND
      :wday_end <= end_day AND
      start_hour <= :hour_start AND
      :hour_end <= end_hour AND
      user_id != :user',
      wday_start: dstart,
      wday_end: dend,
      hour_start: hstart,
      hour_end: hend,
      user: current_user_id
    ).map(&:user)
    available_users << self.where('
      end_day < start_day AND
      :wday_end <= end_day AND
      :hour_end <= end_hour AND
      user_id != :user',
      wday_start: dstart,
      wday_end: dend,
      hour_start: hstart,
      hour_end: hend,
      user: current_user_id
    ).map(&:user)
    available_users
  end

  def enough_for production
    startDayDiff = (production.start_day + 7 - Time.now.wday) % 7
    startHourDiff = 24 * startDayDiff + production.start_hour - Time.now.hour
    startMinuteDiff = 60 * startHourDiff + production.start_minute - Time.now.min

    endDayDiff = (production.end_day + 7 - Time.now.wday) % 7
    endHourDiff = 24 * endDayDiff + production.end_hour - Time.now.hour
    endMinuteDiff = 60 * endHourDiff + production.end_minute - Time.now.min

    startDayDiffFree = (self.start_day + 7 - Time.now.wday) % 7
    startHourDiffFree = 24 * startDayDiffFree + self.start_hour - Time.now.hour
    startMinuteDiffFree = 60 * startHourDiffFree + self.start_minute - Time.now.min

    endDayDiffFree = (self.end_day + 7 - Time.now.wday) % 7
    endHourDiffFree = 24 * endDayDiffFree + self.end_hour - Time.now.hour
    endMinuteDiffFree = 60 * endHourDiffFree + self.end_minute - Time.now.min

    if startMinuteDiffFree <= startMinuteDiff && endMinuteDiff <= endMinuteDiffFree
      return true
    else
      return false
    end
  end
end

app/controllers/free_spots_controller.rb
class FreeSpotsController < ApplicationController
  expose_decorated :free_spot
  expose_decorated :free_spots

  def index; end

  def new; end

  def create
    free_spot.user = current_user
    if free_spot.update_attributes!(free_spot_params)
      flash[:success] = 'Utworzono wolny termin.'
      redirect_to free_spots_path
    else
      render :new
    end
  end

  def update
    if free_spot.update_attributes!(free_spot_params)
      redirect_to free_spots_path
    else
      render :edit
    end
  end

  private

  def free_spot_params
    params.require(:free_spot).permit(
      :start_day,
      :start_hour,
      :end_day,
      :end_hour,
      :start_minute,
      :end_minute,
      :user_id
    )
  end
end

app/views/free_spots/edit.html.haml
.container
  = simple_form_for free_spot, html: { class: 'form-horizontal' } do |f|
    .row
      .col-lg-12
        = f.input :start_day, collection: FreeSpot::DAYS, prompt: 'Wybierz dzień...'
    .row
      .col-lg-12
        = f.input :start_hour, collection: 0..23
    .row
      .col-lg-12
        = f.input :start_minute, collection: 0..59
    .row
      .col-lg-12
        = f.input :end_day, collection: FreeSpot::DAYS, prompt: 'Wybierz dzień...'
    .row
      .col-lg-12
        = f.input :end_hour, collection: 0..23
    .row
      .col-lg-12
        = f.input :end_minute, collection: 0..59
    .row
      .col-lg-12
        = f.submit 'Save', class: 'btn btn-default'

app/views/free_spots/index.html.haml
.container
  %h2 Moje wolne terminy realizacji
  %table.table.table-hover
    %thead
      %tr
        %td Od
        %td Do
        %td Actions
    %tbody
      - free_spots.each do |fs|
        %tr
          %td= fs.start_date
          %td= fs.end_date
          %td
            = link_to edit_free_spot_path(fs), class: 'btn btn-success' do
              %span.glyphicon.glyphicon-pencil
            = link_to free_spot_path(fs), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
              %span.glyphicon.glyphicon-trash
  = link_to new_free_spot_path, class: 'btn btn-lg btn-primary pull-right' do
    %span.glyphicon.glyphicon-plus Dodaj

app/views/free_spots/new.html.haml
.container
  = simple_form_for free_spot, html: { class: 'form-horizontal' } do |f|
    .row
      .col-lg-12
        = f.input :start_day, collection: FreeSpot::DAYS, prompt: 'Wybierz dzień...'
    .row
      .col-lg-12
        = f.input :start_hour, collection: 0..23
    .row
      .col-lg-12
        = f.input :start_minute, collection: 0..59
    .row
      .col-lg-12
        = f.input :end_day, collection: FreeSpot::DAYS, prompt: 'Wybierz dzień...'
    .row
      .col-lg-12
        = f.input :end_hour, collection: 0..23
    .row
      .col-lg-12
        = f.input :end_minute, collection: 0..59
    .row
      .col-lg-12
        = f.submit 'Save', class: 'btn btn-default'