config/routes.rb
Realizafera::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  root 'home#index'

  get 'chief/graphic' => 'chief#graphic'
  get 'graphic' => 'graphics#show'
  get 'my_productions' => 'productions#my_productions'
  get 'user_annulments' => 'productions#user_annulments'
  get 'exchange' => 'productions#exchange'
  get 'available_productions' => 'productions#available_productions'

  resources :productions do
    member do
      get :cancel
      get :claim
    end
  end
  resources :free_spots
end

app/views/layouts/_menu.html.haml
%nav.navbar.navbar-default{ role: 'navigation' }
  .container-fluid
    .navbar-header
      %button.navbar-toggle{ data: { target: '#bs-example-navbar-collapse-1', toggle: 'collapse' }, type: 'button' }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand= link_to 'Realizafera', '/'
    - if current_user
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li.dropdown
            %a.dropdown-toggle{ data: { toggle: 'dropdown' }, href: '#' }
              Akcje
              %b.caret
            = render 'layouts/producer_actions'
        %ul.nav.navbar-nav.navbar-right
          %li
            %a= "Zalogowano jako: #{ current_user.email }"
          %li.dropdown
            %a.dropdown-toggle{ data: { toggle: 'dropdown' }, href: '#' }
              %span.glyphicon.glyphicon-cog
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to 'Zmień hasło', edit_user_registration_path
              %li
                = link_to 'Wyloguj', destroy_user_session_path, method: :delete

app/views/layouts/_producer_actions.html.haml
%ul.dropdown-menu
  %li
    = link_to 'Moje wolne terminy', free_spots_path
    = link_to 'Moje realizacje', my_productions_path
    = link_to 'Moje anulowane realizacje', user_annulments_path
    = link_to 'Wolne realizacje', available_productions_path
    - if user_is_admin?
      = link_to 'Grafik szefa', '/chief/graphic#week'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    %title Realizafera
    = stylesheet_link_tag    'application', media: 'all'
    = include_gon
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/menu'
    .container= render 'shared/messages'
    = yield